travis:
  secure:
    BINSTAR_TOKEN: eZuC8zqpXI19iZff5cE3upVQo0fDXNBUN7HULRMugGwV0LM2YTq+sGyMW4t+4oLiLL5nQhVONX/4IW+OW3ZpbOcudj3RBC4BKxn2NlPne8CN6lNEbl7VS29AixXOPrvyYPVQ8fdTuy1glTO2/RI3fJGcZJgQGlb+fmPp241uO/Q8sWzY5NIlgcQ8PDSLWfk6Xia63uw+A6XIWR2NxyBvgi3AjoBhX5+AW0Uch8Xc95QfNGvXl7pNcqL1+G1d0vNI+X5TVU9RPuxAphU0C3f9t0OXlCZqSDY1I+IuuVOprV7HZy/amcCbDEkeaBubNGwM/FTXYazeZMHbmhUgz8beRyW0wPIBNekwP3lCc2Sx7c5CFyweDjCp7cUJ7pkkZK+semKEwtDTwaF2MUvh+L8vVtpXURG3WcsXjzAiY1GzGLlgGzbQLPlbK02Ii5qgqQu/KGYDJrJiHhLGQOQEVdHCpEr52Fm8cbQmPrphqnYi17MN6hCokWC5bPw9tHkktNrKk0S7y7h2vCr5rivbmdAk8Pac40MIzqmYNcAI16oQdWsE9xhoNM4re2qIuQMNjSmkz9UXZDUSrT4TexzToBwWh1vHRM3bXNfDvzbBahIj2vx20jy8OKtbBKg1qy5VBrA4oiGHesjHxgUQWR6CMf8FYnvn566VYRxm/lwVs03Tt4E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
