travis:
  secure:
    BINSTAR_TOKEN: IZLuKNkvYRWZPibFkGeQvroWIraZxPKTZ7M0tkww1yHUPEn1V2i2nL2e7M5OwAsFaAh/1c31nW3Lx5FpEFBQzn+ayLD2QU57MUseWAukPzOMvNBFutwFRSMv9IgXPL3a9IDLuYj9ed6+QSE1E/x2fz01TuKLjVFP9JCHsYERQac5iLidXmINO0HRaaxq5DdVlbHw4IApBKY6Sfb0WGeRDZCmXgEWfdg814rB38c68iEafyyYNBzdoUltlebugeRg45ablH6UolQ+0W0yd1c1tVGqP06ijjuSg8yRZW8vmEEwYbB0sQiCm+QvSRKz8Cv2B6888H1BH87LdoJ0Jiefy9gSQ1Pn5/7n6vYg9oOh5GQqBtUozVtPN6du1ITwhsd2AIAbRiyaJIfwfQrNGAbAz9Qt1fsyJyqR1C/eb/oWpXjeqZLCYyv7E7wBc9nUPKG3Kncmow2bX0fqajOwGVuEMWgKMPFDBf7e3ZLCcfU3xFYNL7XIW5e1jNTm5Z688E4oB7XtQcrbuA96aOPHOg5NSQeZArqPLr+vWQQM1GgbPgzsnLF/1kNJiahdxhj3Q5I6CnDsSNTWguNVWB2yZBbJUqczL7+nRv+ZZ9HgW6l+MZWdpArAg9PNfotzsrpl0a+dSq9GjKX/Sf4eBZteylVQJ2xifPDMMp1UAFXcCmQ+eS0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
